# Yazi keymap configuration
# See: https://yazi-rs.github.io/docs/configuration/keymap

[[mgr.prepend_keymap]]
on   = ["m", "s"]
run  = "linemode size"
desc = "Linemode: size"

[[mgr.prepend_keymap]]
on   = ["m", "t"]
run  = "linemode mtime"
desc = "Linemode: mtime"

[[mgr.prepend_keymap]]
on   = ["m", "p"]
run  = "linemode permissions"
desc = "Linemode: permissions"

[[mgr.prepend_keymap]]
on   = ["m", "n"]
run  = "linemode none"
desc = "Linemode: none"
